/* Mine Japan — new course shell. Lesson content lives in lessons-data.js. */
const KEY='mine-japan-v2-progress';
const state={view:'home',lesson:1,answers:{}};
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{completed:[]}}catch{return{completed:[]}}}
function save(p){localStorage.setItem(KEY,JSON.stringify(p))}
let progress=load();
const completed=()=>new Set(progress.completed||[]);
const pct=()=>Math.round((completed().size/lessons.length)*100);
function go(view,id){state.view=view;if(id)state.lesson=id;render();window.scrollTo({top:0,behavior:'smooth'});}
function isUnlocked(id){return id===1||completed().has(id-1)}
function complete(id){const s=completed();s.add(id);progress.completed=[...s].sort((a,b)=>a-b);save(progress);}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function renderHome(){return `<section class="hero"><span class="sticker s1">🎀</span><span class="sticker s2">🐟</span><span class="sticker s3">🍦</span><span class="sticker s4">✿</span><div class="hero-card"><div class="hero-eyebrow">JAPANESE NOTEBOOK · LEVEL 1</div><h1>MINE JAPAN</h1><div class="jp-title">日本語 NOTEBOOK</div><p>เรียนภาษาญี่ปุ่นตั้งแต่ศูนย์ ผ่านบทเรียนทีละขั้นในสมุดญี่ปุ่นของเราเอง</p><button class="cta" data-action="course">START LEARNING</button><div class="small" style="margin-top:18px">300 LESSONS · ${completed().size} COMPLETED</div></div></section>`}
function renderCourse(){const done=completed();return `<section><div class="section-head"><div><div class="eyebrow">JAPANESE NOTEBOOK</div><h2>LEVEL 1</h2><div class="small">Beginner → Intermediate · 300 Lessons</div></div><div class="progress-wrap"><div class="progress-meta"><span>COURSE PROGRESS</span><strong>${pct()}%</strong></div><div class="progress"><span style="width:${pct()}%"></span></div></div></div><div class="course-grid">${lessons.map(l=>{const unlocked=isUnlocked(l.id),finished=done.has(l.id);return `<article class="lesson-card ${unlocked?'':'locked'}" data-lesson="${l.id}"><span class="lesson-num">LESSON ${String(l.id).padStart(3,'0')}</span><span class="status ${finished?'done':unlocked?'open':''}">${finished?'✓ DONE':unlocked?'OPEN':'LOCKED'}</span><h3>${esc(l.title||'Lesson '+l.id)}</h3><p>${esc(l.subtitle||'Japanese lesson')}</p></article>`}).join('')}</div></section>`}
function sectionHTML(s,i){const t=s.type||'text';let body='';if(t==='practice'){const key=`p-${i}`;body=`<div class="practice"><strong>ลองตอบ</strong><p>${esc(s.question)}</p>${(s.choices||[]).map((c,j)=>`<button class="choice" data-practice="${key}" data-answer="${j}">${esc(c)}</button>`).join('')}<div class="practice-result" id="result-${key}"></div></div>`}else if(s.cards||t==='concept'){const cards=s.cards||[];body=cards.length?`<div class="concept-grid">${cards.map(c=>`<div class="concept-card"><strong>${esc(c.title)}</strong><p>${c.text||''}</p></div>`).join('')}</div>`:(s.content||s.html||s.text||'')}else{body=s.content||s.html||s.text||''}return `<div class="content-block"><h2>${esc(s.title||'')}</h2><div>${body}</div></div>`}
function renderLesson(){const l=lessons.find(x=>x.id===state.lesson)||lessons[0],done=completed().has(l.id);return `<section class="lesson-layout"><button class="back" data-action="course">← Back to Course</button><article class="lesson-sheet"><div class="lesson-kicker"><span>LESSON ${String(l.id).padStart(3,'0')}</span><span>${esc(l.level||'MINE JAPAN')}</span></div><h1>${esc(l.title||'')}</h1><p class="lesson-subtitle">${esc(l.subtitle||'')}</p>${l.objective?.length?`<div class="objective"><strong>วันนี้จะได้อะไร</strong><ul>${l.objective.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}<div class="lesson-content">${(l.sections||[]).map(sectionHTML).join('')}</div><div class="lesson-nav"><button class="nav-btn" data-prev="${l.id}" ${l.id<=1?'disabled':''}>← PREVIOUS</button><button class="nav-btn primary" data-next="${l.id}">${l.id<lessons.length?'COMPLETE & NEXT →':'COMPLETE COURSE ✓'}</button></div></article></section>`}
function renderProgress(){return `<section class="progress-page"><div class="section-head"><div><div class="eyebrow">YOUR NOTEBOOK</div><h2>PROGRESS</h2></div></div><div class="big-progress"><div class="big-number">${pct()}%</div><p>${completed().size} of ${lessons.length} lessons completed.</p><div class="progress"><span style="width:${pct()}%"></span></div>${completed().size===lessons.length?'<div class="milestone"><strong>Course complete!</strong><br>มึงเรียนครบ 300 บทแล้ว 🎉</div>':'<div class="milestone"><strong>Keep going.</strong><br>บทถัดไปที่เปิดอยู่: Lesson '+(completed().size+1)+'</div>'}</div></section>`}
function render(){const app=document.querySelector('#app');app.innerHTML=state.view==='home'?renderHome():state.view==='course'?renderCourse():state.view==='progress'?renderProgress():renderLesson()}
document.addEventListener('click',e=>{const a=e.target.closest('[data-action]');if(a){const v=a.dataset.action;if(v==='home')go('home');if(v==='course')go('course');if(v==='progress')go('progress');return}const card=e.target.closest('[data-lesson]');if(card){const id=Number(card.dataset.lesson);if(isUnlocked(id))go('lesson',id);return}const next=e.target.closest('[data-next]');if(next){const id=Number(next.dataset.next);complete(id);if(id<lessons.length)go('lesson',id+1);else go('progress');return}const prev=e.target.closest('[data-prev]');if(prev){const id=Number(prev.dataset.prev);if(id>1)go('lesson',id-1);return}const choice=e.target.closest('[data-practice]');if(choice){const id=Number(state.lesson),l=lessons.find(x=>x.id===id);const block=choice.closest('.practice');const buttons=[...block.querySelectorAll('.choice')];const answer=Number(choice.dataset.answer);let data=null;for(const s of l.sections||[]){if(s.type==='practice'){if(!data)data=s;else { /* first practice is enough for this lightweight interaction */ }}}if(data){buttons.forEach((b,i)=>{b.disabled=true;if(i===data.answer)b.classList.add('correct')});const r=block.querySelector('.practice-result');r.textContent=answer===data.answer?'ถูกต้อง! เก่งมาก ♡':'ยังไม่ถูก ลองดูคำตอบที่ถูกแล้วอ่านคำอธิบายอีกครั้ง';if(data.explanation)r.textContent+=` ${data.explanation}`}}});
render();
